### ISSUE TITLE
CSV Import of array for matrix

### ISSUE THREAD

**Issue by mwtilton** [brean/python-pathfinding#8] opened 2017-12-27 00:39 UTC
I created a matrix array in a CSV file as I needed to make the array for ~500 different points that may need to change on a bi-monthly basis, so csv file feels like the best way to maintain this as opposed to manually creating and updating it within `my_pathfinding_file.py`. 

I used numpy and pandas to read the file and create the array, no problem; however when it spits out the array it looks like this:
`matrix = [`
`[1 0 0 0 1]`
`]`

instead of
`matrix = [`
`[1, 0, 0, 0, 1]`
`]`

Which returns an error when you try to run it through the `grid.py` portion of your script. As best as I can understand it the `grid.py` script requires the commas to be associated to a `list` type of format, not an array of numbers; or what maybe considered a `tuple`.

Would it be possible to add in this sort of functionality? I have looked into the articles below to best resolve the issue but my understanding of python is too limited to understand the greater problem nor how to implement it into the code you have already created.
[Grid from counting points](https://gis.stackexchange.com/questions/257466/creating-counting-grid-from-set-of-points-using-numpy)
[CSV appending rows option](https://stackoverflow.com/questions/44634141/python-appending-comma-character-to-a-row-in-csv-file
)

**Comment by charlietoast** [comment] 2017-12-27 04:50
This seems to be the current working solution:
```
import pandas
import numpy as np
import csv

from pathfinding.core.diagonal_movement import DiagonalMovement
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder

with open("PathToCSV",'r') as f:
    reader = csv.reader(f, delimiter=',')
    list_reader = list(reader)
    mtx = [list(map(int, x)) for x in list_reader]

grid = Grid(matrix=mtx)

start = grid.node(0, 0)
end = grid.node(2, 2)

finder = AStarFinder(diagonal_movement=DiagonalMovement.never)
path, runs = finder.find_path(start, end, grid)

print(grid.grid_str(path=path, start=start, end=end))
print('operations:', runs, 'path length:', len(path))
```

**Comment by brean** [comment] 2017-12-27 09:39
the python-print for numpy does not print the commas, but the data is seperated. I think it should be possible to use numpy arrays so I will investigate and reopen this issue.
Can you provide me with the non-working code and/or error message?

**Comment by charlietoast** [comment] 2017-12-28 10:49
I will upload this a little later today. Thanks for the quick response!

**Comment by charlietoast** [comment] 2017-12-28 22:34
This is the code I was trying to use:

```
import pandas
import numpy as np

from pathfinding.core.diagonal_movement import DiagonalMovement
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder

mtrx = np.array(pandas.io.parsers.read_csv("PATHTOCSV")).astype("str")


grid = Grid(matrix=mtrx)

start = grid.node(0, 0)
end = grid.node(2, 2)

finder = AStarFinder(diagonal_movement=DiagonalMovement.never)
path, runs = finder.find_path(start, end, grid)

print('operations:', runs, 'path length:', len(path))
print(grid.grid_str(path=path, start=start, end=end))
```

And this is the error message I receive:

```
Traceback (most recent call last):
  File "c:\Users\Public\Documents\PythonScripts\python-pathfinding-master\testing_path_DONOTTOUCH.py", line 11, in <module>
    grid = Grid(matrix=mtrx)
  File "c:\Users\Public\Documents\PythonScripts\python-pathfinding-master\pathfinding\core\grid.py", line 39, in __init__
    self.nodes = build_nodes(self.width, self.height, matrix)
  File "c:\Users\Public\Documents\PythonScripts\python-pathfinding-master\pathfinding\core\grid.py", line 13, in build_nodes
    if matrix:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by brean** [comment] 2017-12-29 11:26
I created a unit-test based on your code - [see csv_pandas_test.py](https://github.com/brean/python-pathfinding/blob/master/test/csv_pandas_test.py).
The current version on master should work for you.
Feel free to play around, test it and close this if your issue is resolved.

**Comment by charlietoast** [comment] 2017-12-29 11:41
Thanks. I will give that a try.

**Comment by brean** [comment] 2018-02-09 10:43
I assume the issue is resolved, so I close this issue now.

**Closed by brean** 2018-02-09 10:43 UTC
Labels: bug

**Comment by mwtilton** [comment] 2018-02-10 20:01
Yes this fixed the problem. Sorry for late reply, got side-tracked on other porjects xD Thansk for the help!
